# Generated by Django 5.0.4 on 2024-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='isRating',
            field=models.BooleanField(default=False),
        ),
    ]
