# Generated by Django 5.0.4 on 2024-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='phone',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
