# Generated by Django 5.0.4 on 2024-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_drink_descriptions_alter_drink_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='email',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='producer',
            name='fb',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='producer',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='insta',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='producer',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='phone',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
