# Generated by Django 5.0.4 on 2024-06-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_questionnaire_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='app.region'),
        ),
    ]
